server:
  port: 443
  ssl:
    key-store:
    key-store-password:
    key-store-type:

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiaohui_blog?serverTimezone=UTC
      username: 账号
      password: 密码
      #配置初始化大小/最小/最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      useGlobalDataSourceStat: true

  redis:
    host: localhost
    port: 6379
    password: 密码
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
    database: 1

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    cache: false #关闭缓存
    suffix: .html
  freemarker:
    checkTemplateLocation: false



#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  retrunPageInfo: check

mybatis:
  type-aliases-package: com.xiaohuis.entity
  mapper-locations: classpath:com/xiaohuis/dao/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
